Unable to compile with -Werror flag
Framework is not compiling because auf unused parameter warning and -Werror compile flag.
benchmark.cc:866:8: error: unused parameter ‘b’ [-Werror=unused-parameter]
 double Benchmark::MeasurePeakHeapMemory(const Instance& b)