benchmark.h: mark virtual functions implementation as override
This prevent to trigger an error with recent GCC (gcc 9.x) with -Werror=suggest-override flag

see
````
gbenchmark/include/benchmark/benchmark.h:1005:16: error: ‘virtual void benchmark::internal::FunctionBenchmark::Run(benchmark::State&)’ can be marked override [-Werror=suggest-override]
 1005 |   virtual void Run(State& st);
      |                ^~~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors
````